### PR TITLE
Install Script for yiimp mining pool

### PR DESCRIPTION
**Pull request by oakey22**

### CODE REVIEW

**Comment by lyoshenka** [comment]
@oakey22 please add instructions to readme on  how to use this install script, if any requirements changed, etc.

**Comment by oakey22** [comment]
Yes no problem, I will add them later on, just getting the ground work sorted first.

**Comment by tzarebczan** [comment]
@oakey22 did you ever get a chance to follow up on this?

**Comment by oakey22** [comment]
Will get on this tomorrow, and get it updated

**Comment by lyoshenka** [comment]
@oakey22 whats the status on this PR?

**Comment by lyoshenka** [comment]
@oakey22 @tzarebczan bump

**Comment by oakey22** [comment]
I am just updating the readme, the script is now complete and has been altered on here. I will close this PR when i have done the readme

**Comment by oakey22** [comment]
This can now be closed, the readme is done and the install script too.

**Pull request closed without merging**
